In [3]:
import pandas as pd 
root_path = "C:\\Users\\shibiyasaju\\Desktop\\DATA ANALYTICS\\main case study\\Road Accident Analytics and Road Safety Optimization in India"
df = pd.read_csv(f"{root_path}\\data\\csv\\accident_prediction_india.csv")

df.head()

,State Name,City Name,Year,Month,Day of Week,Time of Day,Accident Severity,Number of Vehicles Involved,Vehicle Type Involved,Number of Casualties,...,Road Type,Road Condition,Lighting Conditions,Traffic Control Presence,Speed Limit (km/h),Driver Age,Driver Gender,Driver License Status,Alcohol Involvement,Accident Location Details
0,Jammu and Kashmir,Unknown,2021,May,Monday,1:46,Serious,5,Cycle,0,...,National Highway,Wet,Dark,Signs,61,66,Male,NaN,Yes,Curve
1,Uttar Pradesh,Lucknow,2018,January,Wednesday,21:30,Minor,5,Truck,5,...,Urban Road,Dry,Dusk,Signs,92,60,Male,NaN,Yes,Straight Road
2,Chhattisgarh,Unknown,2023,May,Wednesday,5:37,Minor,5,Pedestrian,6,...,National Highway,Under Construction,Dawn,Signs,120,26,Female,NaN,No,Bridge
3,Uttar Pradesh,Lucknow,2020,June,Saturday,0:31,Minor,3,Bus,10,...,State Highway,Dry,Dark,Signals,76,34,Female,Valid,Yes,Straight Road
4,Sikkim,Unknown,2021,August,Thursday,11:21,Minor,5,Cycle,7,...,Urban Road,Wet,Dusk,Signs,115,30,Male,NaN,No,Intersection

In [4]:
df.columns

Index(['State Name', 'City Name', 'Year', 'Month', 'Day of Week',
       'Time of Day', 'Accident Severity', 'Number of Vehicles Involved',
       'Vehicle Type Involved', 'Number of Casualties', 'Number of Fatalities',
       'Weather Conditions', 'Road Type', 'Road Condition',
       'Lighting Conditions', 'Traffic Control Presence', 'Speed Limit (km/h)',
       'Driver Age', 'Driver Gender', 'Driver License Status',
       'Alcohol Involvement', 'Accident Location Details'],
      dtype='str')

In [2]:
df["Number of Casualties"].describe()

count    3000.000000
mean        5.066000
std         3.214097
min         0.000000
25%         2.000000
50%         5.000000
75%         8.000000
max        10.000000
Name: Number of Casualties, dtype: float64

In [5]:
severity_stats = (
    df.groupby("Accident Severity")["Number of Casualties"]
      .agg(["count", "mean", "median", "std", "min", "max"])
)

severity_stats

                   count      mean  median       std  min  max
Accident Severity
Fatal                985  5.075127     5.0  3.221252    0   10
Minor               1034  5.011605     5.0  3.246543    0   10
Serious              981  5.114169     5.0  3.174711    0   10

In [6]:
road_stats = (
    df.groupby("Road Type")["Number of Casualties"]
      .agg(["count", "mean", "median", "std", "min", "max"])
      .sort_values("mean", ascending=False)
)

road_stats

                  count      mean  median       std  min  max
Road Type
National Highway    749  5.204272     5.0  3.280909    0   10
Urban Road          712  5.074438     5.0  3.218061    0   10
State Highway       771  5.011673     5.0  3.185783    0   10
Village Road        768  4.977865     5.0  3.174340    0   10

In [7]:
weather_stats = (
    df.groupby("Weather Conditions")["Number of Casualties"]
      .agg(["count", "mean", "median", "std"])
      .sort_values("mean", ascending=False)
)

weather_stats

                    count      mean  median       std
Weather Conditions
Stormy                611  5.148936     5.0  3.222220
Hazy                  608  5.116776     5.0  3.241694
Foggy                 576  5.057292     5.0  3.217104
Rainy                 631  5.052298     5.0  3.251684
Clear                 574  4.947735     5.0  3.138021

In [8]:
vehicle_stats = (
    df.groupby("Vehicle Type Involved")["Number of Casualties"]
      .agg(["count", "mean", "median", "std"])
      .sort_values("mean", ascending=False)
)

vehicle_stats

                       count      mean  median       std
Vehicle Type Involved
Car                      393  5.206107     5.0  3.221542
Auto-Rickshaw            449  5.131403     5.0  3.137919
Bus                      442  5.126697     5.0  3.244009
Truck                    449  5.037862     5.0  3.226687
Two-Wheeler              427  5.011710     5.0  3.149984
Pedestrian               419  4.985680     5.0  3.349610
Cycle                    421  4.966746     5.0  3.184611

In [9]:
severity_percentage = (
    df["Accident Severity"]
    .value_counts(normalize=True) * 100
)

severity_percentage

Accident Severity
Minor      34.466667
Fatal      32.833333
Serious    32.700000
Name: proportion, dtype: float64

In [10]:
road_percentage = (
    df["Road Type"]
    .value_counts(normalize=True) * 100
)

road_percentage

Road Type
State Highway       25.700000
Village Road        25.600000
National Highway    24.966667
Urban Road          23.733333
Name: proportion, dtype: float64

In [11]:
fatal = (df["Accident Severity"] == "Fatal").sum()

minor = (df["Accident Severity"] == "Minor").sum()

fatal_to_minor_ratio = fatal / minor

fatal_to_minor_ratio

np.float64(0.9526112185686654)

In [12]:
yearly_accidents = (
    df.groupby("Year")
      .size()
      .reset_index(name="Accidents")
)

yearly_accidents

   Year  Accidents
0  2018        479
1  2019        468
2  2020        526
3  2021        522
4  2022        521
5  2023        484

In [13]:
yearly_accidents["YoY Growth %"] = (
    yearly_accidents["Accidents"]
    .pct_change() * 100
)

yearly_accidents

   Year  Accidents  YoY Growth %
0  2018        479           NaN
1  2019        468     -2.296451
2  2020        526     12.393162
3  2021        522     -0.760456
4  2022        521     -0.191571
5  2023        484     -7.101727

In [14]:
highest_year = yearly_accidents.loc[
    yearly_accidents["Accidents"].idxmax()
]

highest_year

Year            2020.000000
Accidents        526.000000
YoY Growth %      12.393162
Name: 2, dtype: float64

In [15]:
severity_year = (
    pd.crosstab(
        df["Year"],
        df["Accident Severity"],
        normalize="index"
    ) * 100
)

severity_year

Accident Severity      Fatal      Minor    Serious
Year
2018               32.359081  34.864301  32.776618
2019               28.632479  34.615385  36.752137
2020               30.988593  35.551331  33.460076
2021               35.249042  32.567050  32.183908
2022               32.245681  33.973129  33.781190
2023               37.396694  35.330579  27.272727

In [16]:
state_casualties = (
    df.groupby("State Name")["Number of Casualties"]
      .sum()
      .sort_values(ascending=False)
)

state_casualties

State Name
Goa                  585
Delhi                566
Sikkim               548
Puducherry           540
Uttarakhand          540
Gujarat              525
Kerala               520
West Bengal          503
Rajasthan            501
Jammu and Kashmir    499
Nagaland             496
Tamil Nadu           493
Jharkhand            493
Haryana              493
Karnataka            490
Meghalaya            488
Uttar Pradesh        479
Manipur              472
Maharashtra          468
Madhya Pradesh       461
Mizoram              460
Assam                449
Bihar                445
Chhattisgarh         441
Odisha               441
Telangana            432
Himachal Pradesh     429
Punjab               412
Tripura              398
Andhra Pradesh       384
Chandigarh           382
Arunachal Pradesh    365
Name: Number of Casualties, dtype: int64

In [17]:
df["Fatal_Flag"] = (
    df["Accident Severity"] == "Fatal"
).astype(int)

In [18]:
weather_fatality = (
    df.groupby("Weather Conditions")["Fatal_Flag"]
      .mean() * 100
)

weather_fatality.sort_values(ascending=False)

Weather Conditions
Foggy     33.854167
Stormy    33.224223
Clear     33.101045
Hazy      32.894737
Rainy     31.220285
Name: Fatal_Flag, dtype: float64